#fazer uma tabuada
numero = float(input('Insira o número desejado realizar a sua tabuada:'))
print('-='*15)
print('{:.0f} x {} = {:.0f}'.format(numero, 1, numero*1))
print('{:.0f} x {} = {:.0f}'.format(numero, 2, numero*2))
print('{:.0f} x {} = {:.0f}'.format(numero, 3, numero*3))
print('{:.0f} x {} = {:.0f}'.format(numero, 4, numero*4))
print('{:.0f} x {} = {:.0f}'.format(numero, 5, numero*5))
print('{:.0f} x {} = {:.0f}'.format(numero, 6, numero*6))
print('{:.0f} x {} = {:.0f}'.format(numero, 7, numero*7))
print('{:.0f} x {} = {:.0f}'.format(numero, 8, numero*8))
print('{:.0f} x {} = {:.0f}'.format(numero, 9, numero*9))
print('{:.0f} x {} = {:.0f}'.format(numero, 10, numero*10))
print('-='*15)
